#!/usr/bin/env bash

git__ () {
  __exec git "$@"
}

# updates the worktree core, or otherwise simply .git file
worktreeupdate__ () {
  local newpath=$1
  git__ config --local --unset core.worktree
  git__ config --local core.bare true
  git__ config --local core.repository $newpath
}

date__help='@arg date (e.g. 2 days ago) @does ammend the commit with the given date'
date__ () {
  local date="$1"
  # we don't use local variable to capture the error code
  newdate="$(date --date="$date")"
  test $? -eq 0 || return -1
  GIT_COMMITTER_DATE="$newdate" git__ commit --amend --no-edit --date="$newdate"
}

barebranch__help='@does rename HEAD branch on a bare repository.'
barebranch__ () {
  read -p 'What branch to change to? ' branch
  : 'https://stackoverflow.com/a/3302018/257479'
  git__ symbolic-ref HEAD refs/heads/$branch
}

log__ () {
  git__ log --pretty=fuller
}

diff__ (){
  : 'https://stackoverflow.com/a/25634420/257479'
  git__ diff --color-words='[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+' "$@"
}

newfile__help='@arg filenames @does adds the file path to index without the content.'
newfile__ () {
  : 'https://stackoverflow.com/a/6440500/257479'
  local files="$@"
  git__ add --intent-to-add $files
}

serch__help='@arg search_term @does grep the search term in history'
search__ () {
  : 'https://stackoverflow.com/a/2929502/257479'
  : '@TODO accept subtree as an argument'
  local search=$1
  git__ grep $search $(git rev-list --all)
}

. undies
